name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    permissions:
      contents: write
      packages: write
    uses: dcc-bigfred/.github/.github/workflows/rust-oras-release.yml@v1
    with:
      oci_image: ghcr.io/dcc-bigfred/microdns-linux-arm64
      oci_title: microdns
      oci_layers: microdns-linux-arm64=application/vnd.dcc-bigfred.microdns.linux.arm64.v1
      oci_elf_layers: microdns-linux-arm64
      oci_elf_section: .microdns.version
      ci_workflow: ci.yml
      ci_scripts_ref: v1
    secrets: inherit
